### ISSUE TITLE
Cloudflare Worker support

### ISSUE THREAD

**Issue by fetimo** [Hexagon/entsoe-api-client#4]
Hey! Just wanted to say this is an absolutely fantastic library. Everything you could wish for from a client and makes this arcane API bearable to work with. 

I've forked the library as the inclusion of undici was causing a deployment to Cloudflare Workers to fail. Is it possible that this could be something that is configurable at runtime or to generate two separate builds? No worries if not :)

**Comment by Hexagon** [comment]
Great to hear :)

I guess it would be possible to add a node build without undici. I dont remember for sure, but I think the only reason undici is included, is to support order versions of node not supporting fetch ootb. If you want to try it out yourself it should "just" be a matter of changing the undici-flag in scripts/build_npm, and running deno task build :)

**Comment by fetimo** [comment]
Exactly :D that's what I've done and it works great but I didn't want to publish it as a new package to avoid confusion. Another thought, a few libraries let you pass in a fetch implementation. It'd be a breaking change but I wonder if that'd be an option rather than bundling in undici? I'm happy to create a PR if you think that idea is workable.

**Comment by Hexagon** [comment]
I think the best/simplest option would be to drop undici and older versions of node altogether. Then call it 1.0, and add a note in the readme to use 0.x with order versions of node. V18 is LTS, and that supports fetch :)

If you want to make these changes in a PR (including the change to 1.0 in readme), i can release a new version.
